backend:
  name: git-gateway   # Netlify Identity + Git Gateway 사용
  branch: main

media_folder: "images/uploads"   # 실제 GitHub 레포 경로
public_folder: "/images/uploads" # 브라우저에서 접근 가능한 경로

collections:
  - name: "posts"
    label: "게시물"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "내용", name: "body", widget: "markdown" }
